#!/bin/sh

#. ./spelunking.sh

echo "=========================================="
echo "= SMOKE TESTS                            ="
echo "=========================================="

for script in *.sh ; do
   ./$script
done

echo "=========================================="
