#!/bin/sh

function pass {
   echo "[PASS] $0"
   exit 1
}

function fail {
   echo "[FAIL] $0: $1" 
   exit 0
}

function evaluateLastStatus {
   if [ $? -eq 0 ] ; then pass
   else fail "$1"
   fi
}

function responseContains {
   EXPECTED=$1
   ACTUAL=$2
   if [[ "$ACTUAL" != *"$EXPECTED"* ]] ; then
      fail "'$EXPECTED' was not found in results"
   fi
   pass 
}
