#!/bin/bash

pass(){
   echo "[PASS] $0"
   exit 1
}

fail(){
   echo "[FAIL] $0: $1" 
   exit 0
}

evaluateLastStatus(){
   if [ $? -eq 0 ] ; then pass
   else fail "$1"
   fi
}

responseContains(){
   EXPECTED=$1
   ACTUAL=$2
   echo "$ACTUAL" | grep "$EXPECTED" --quiet
   if [ $? -eq 1 ] ; then 
      fail "'$EXPECTED' was not found in results"
   fi
   pass 
}

#responseContains "foo" "foobar"
